### ISSUE TITLE
Closing a pool after checking out/returning pool

### ISSUE THREAD

**Issue by lizard12995** [rstudio/pool#113]
I may be going about this the wrong way, but at one point in my code, I use poolCheckout, create some temporary tables, and then use poolReturn. When I use poolReturn though, the connection becomes a "Formal class PqConnection" rather than an environment. When I try to close the pool at the end (poolClose), it can't close that connection. Is there some alternative way to close after I've returned it?

**Comment by lizard12995** [comment]
happy to post a reprex if that's more helpful

**Comment by hadley** [comment]
@lizard12995 please start with a reprex
