### ISSUE TITLE
Add pseduo load balancing

### ISSUE THREAD

**Issue by suprtomato** [rstudio/pool#127]
It would be fantastic if we could provide a vector of host names and each new connections could be pulled from the list of these hosts either in order or random from a list where number_of_connections == min(number_of_connections).
A further benefit would be to 'fall back' on other connections if one of the hosts is failing to connect. Some of this functionality can be managed in JDBC, but it is very difficult in ODBC without a dedicated software or hardware load balancer.
Use cases include distributed databases such as Impala where connections to individual nodes is the primary or only method.
This need not be aware of the content of the query or the actual load on the system.

**Comment by jcheng5** [comment]
You can achieve something like this by using `poolCreate` directly instead of `dbPool`:

```r
library(pool)

pool <- poolCreate(
  function() {
    host <- sample(c(
      # Hostnames go here...
      "shiny-demo.csa7qlmguqrf.us-east-1.rds.amazonaws.com",
      "shiny-demo.csa7qlmguqrf.us-east-1.rds.amazonaws.com",
      "shiny-demo.csa7qlmguqrf.us-east-1.rds.amazonaws.com"
    ), 1)

    DBI::dbConnect(
      drv = RMySQL::MySQL(),
      dbname = "shinydemo",
      host = host,
      username = "guest",
      password = "guest"
    )
  },
  minSize = 4
)

dbGetQuery(pool, "SELECT * from City LIMIT 5;")
```

Hope that meets your needs.

**Comment by suprtomato** [comment]
Yes, this meets the nature of the request.  There is an issue with implementation.
My intent was to use pools to enable parallelization. My implementation will execute, but appears to hang after execution.  Maybe in the cleanup stage?
Do you have alternative suggestion for implementing pools with parallelization.
query_vector <- c("Select 'a'", "Select 'b'", "Select 'c'", "Select 'd'")
query_result_mcl <- parallel::mclapply(query_vector,
                                         DBI::dbGetQuery,
                                         con=pool,
                                         mc.preschedule = FALSE,
                                         mc.cores = 4)
