### ISSUE TITLE
poolWithTransaction and fork/multicore

### ISSUE THREAD

**Issue by mmuurr** [rstudio/pool#128]
I know that many DB driver packages warn against sharing one connection across multiple processes, but I'm also trying to find a pattern to allow for some multicore parallelism for some DB operations. My initial thought was that provided no connection was _simultaneously_ used across distinct processes, this might work. My initial script looked like the below and indeed, it works fine:
```R
CONN_COUNT  <- 2
CORE_COUNT  <- 2
QUERY_COUNT <- 10

dbiconnpool <- pool::dbPool(RPostgres::Postgres(), service = "my.psql.service", maxSize = CONN_COUNT)

# un-comment the following line to generate downstream SSL errors:
#initial_query <- DBI::dbGetQuery(dbiconnpool, "select 1")

foo <- parallel::mclapply(seq_len(QUERY_COUNT), function(i) {
  pool::poolWithTransaction(dbiconnpool, function(conn) {
    DBI::dbGetQuery(conn, "select 1")
  })
}, mc.cores = CORE_COUNT)

foo  ## either a collection of SSL errors or a collection of 1x1 dataframes with value 1.
```

However, if the `initial_query <- ...` line is un-commented out -- i.e. an upstream block where the `dbiconnpool` object fetches (and returns to the pool) a connection for a query -- **only now** the downstream querying fails do to various SSL errors reminiscent of https://github.com/jeroen/curl/issues/131.

I'm a bit stumped as to why this example works when `initial_query <- ...` is skipped. My first guess was that the SSL connections are PID-dependent and I was getting 'lucky' with the multicore approach where each forked process was always fetching the same connection from {pool}, but the errors occur even when `initial_query <- ...` line is present and `CONN_COUNT <- 1` ... in such a case the `mclapply` call bypasses any actual forking, and so the PID is constant.

I haven't yet tried to replicate this on a non Mac OS X system (where my SSL library is the system's LibreSSL (v2.8.3)).

Has anyone else used {pool} in such a fashion to manage distinct database connections with multicore parallelism?

I can ultimately do this myself by pre-chunking my data into `CONN_COUNT` groups while also keeping `CORE_COUNT < CONN_COUNT` and having each parallel-executing group manage opening and closing its own DB connection (i.e. similar in spirit to `poolWithTransaction()`).
But before going down that path I figured I'd ask for thoughts here, as the `initial_query` oddity above is still quite confusing to me.

<details>
<summary>sessionInfo()</summary>
<pre>
 R version 4.0.3 (2020-10-10)
 Platform: x86_64-apple-darwin19.6.0 (64-bit)
 Running under: macOS Big Sur 10.16

 Matrix products: default
 BLAS:   /usr/local/Cellar/openblas/0.3.13/lib/libopenblasp-r0.3.13.dylib
 LAPACK: /usr/local/Cellar/r/4.0.3_2/lib/R/lib/libRlapack.dylib

 locale:
 [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

 attached base packages:
 [1] stats     graphics  grDevices utils     datasets  methods   base

 loaded via a namespace (and not attached):
  [1] bit_4.0.4        compiler_4.0.3   R6_2.5.0         generics_0.1.0   hms_0.5.3
  [6] later_1.1.0.1    parallel_4.0.3   DBI_1.1.0        Rcpp_1.0.6       bit64_4.0.5
 [11] lubridate_1.7.10 vctrs_0.3.8      blob_1.2.1       pkgconfig_2.0.3  rlang_0.4.10
 [16] pool_0.1.6       RPostgres_1.3.1
</pre>
</details>

**Comment by hadley** [comment]
Using multicore parallelism for pool is out of scope, so unfortunately we can't offer any advice.
