### ISSUE TITLE
Spurious warnings about object activation/validation

### ISSUE THREAD

**Issue by D3SL** [rstudio/pool#130]
I've been using this package regularly for a bit over a year and as far as I can tell everything works fine, but for some reason once I create a connection I'll start getting this warning short while in the console. There don't appear to be any errors, the connection seems to work fine, as near as I can tell it's just a bit of an annoyance to need to hit enter or ctrl+c on that line and clear it every while.

Is there a configuration error I've made somewhere, or could this be related to something on the (fairly old) mysql DBs I'm connecting to?

```
Warning: It wasn't possible to activate and/or validate the object. 
Trying again with a new object.     
```

**Comment by jcheng5** [comment]
Guessing the server is timing out the connection? If it’s working fine, that’s good, it means pool is detecting the situation and gracefully recovering. I suppose we could make that message optional?

**Comment by D3SL** [comment]
I have no idea myself, [this](https://community.rstudio.com/t/pool-should-have-option-to-always-validate-on-fetch/32051) and [this](https://stackoverflow.com/questions/54988978/reconnect-to-postgresql-database-with-rs-pool-package) are the only two valid mentions I've found and neither seems to match my scenario. I'm connecting to a pretty old MYSQL server (v5) in case that's relevant.

In any case it seems harmless, despite taking over the `R$>` line it doesn't seem to hurt anything even if it pops in while input's being relayed to the console.
