### ISSUE TITLE
Since R 4.1.3 installed, unknown encoding instead of UTF-8

### ISSUE THREAD

**Issue by JamesHM1995** [rstudio/pool#131]
Hello,
I uninstalled R 4.1.2 and installed 4.1.3. Since then, despite restarting R, reinstalling all my packages (including pool), if I load a table from our company DB, it doesn't display accents properly. Previously, it properly used UTF-8. My colleague still has 4.1.2 and doesn't have my issue.
I tried returning the encoding from a `tibble()` using the `Encoding()` function, and it returns "unknown" for each observation.

Am I missing an easy setting I could add, or is it indeed an issue with the latest version of R?

**Comment by Afka-be** [comment]
Hello, 
I suspect the culprit might be RMySQL package.

I've been using pool and R (version 4.1.0) and when I was using RSQLite to connect to my SQLite database, UTF8 worked properly.
When I migrated my SQLite database to MySQL (using UTF8 as charset) and began connecting through RMySQL, the issue appeared. I still haven't been able to solve the problem but I hope I might help a bit with this.

**Comment by JamesHM1995** [comment]
Hello,
I tried your solution after installing R 4.2.0, by which point it also worked with the RMySQL package. However, I'll be switching over to the RMariaDB package, it does seem to be much more reliable. 

Thank you for the help!
