### ISSUE TITLE
Call of stored procedures gives `Commands out of sync` error

### ISSUE THREAD

**Issue by vanhry** [rstudio/pool#134]
Hello everyone!
I have a lot of stored procedures call in my code. Now I am going to switch to `pool` library instead of regular DBI calls. 
And I faced with the problem. The first run of code below works fine, but the second one gives me an error.
```shell
Error: Commands out of sync; you can't run this command now [2014]
```

My code that executes several times

```R

query <- sqlInterpolate(con, "CALL GetInfo(?);", user)
df_result <- dbGetQuery(con, query)

```

Code with `poolCheckout` and `poolReturn` gives me the same error after first successful call
```R
con_pool <- poolCheckout(con)
query <- sqlInterpolate(con_pool, "CALL GetInfo(?);", user)
df_result <- dbGetQuery(con_pool, query)
poolReturn(con_pool)
```

global initialization of pool in **global.R**:
```R
con <- dbPool(drv=RMariaDB::MariaDB,
                        ...)
onStop(function() {
  poolClose(con)
})
```

I will appreciate any help from your side!

**Comment by vanhry** [comment]
I found the solution only for RMySQL (which deprecated and I don't want to use it) [solution link](https://github.com/r-dbi/RMySQL/issues/163#issuecomment-347332175)

Here you can find similar issue in RMariaDB, and actually, I guess my problem more related to RMariaDB package
[RMariaDB issue](https://github.com/r-dbi/RMariaDB/issues/166)

**Comment by jcheng5** [comment]
Yeah, this seems not solvable from pool. I made a comment on the RMariaDB issue.
