### ISSUE TITLE
Connect using certificates and keys

### ISSUE THREAD

**Issue by koseri** [rstudio/pool#14]
I need to connect to a remote postgres database (perhaps #7 ), which I currently generate like this:

```
 psql -U my_db_username -p 5432 -h 111.222.33.4 'sslmode =require dbname = my_dbname sslcert=/path/to/certs/my_cert.crt sslkey=/path/to/certs/my_key.key'

```

I can't quite figure out where you're currently generating the connection string so I could not do it myself.  I'd love to help with #7 if this is what it refers to. :-)

**Comment by bborgesr** [comment]
So this may seem a little confusing at first, but bear with me: I don't actually construct the connection string -- the database capabilities of `pool` are largely wrapping around the same-name methods in `DBI`, which most times only defines the S4 generics, whose methods are actually implemented by the DBI-compliant drivers (in your case, this would be `RPostgreSQL`). So if you can connect to your database using a `DBI` call to `dbConnect()`, you should be able to use exactly the same arguments in a call to `dbPool()`. If you can't use `dbConnect`, then the issue probably has to do with the driver implementation in `RPostgreSQL`.

**Comment by koseri** [comment]
I am able to connect in a variety of ways, but since we're already using dplyr you've provided the hint I needed to set up a successful remote connection:

```
username <- "foo"
db_host <- "111.22.33.44"
db <- "my_db"
certs_path <- "/path/to/certs"

pool <- dbPool(
  drv = "PostgreSQL",
  host = db_host,
  dbname =   paste0( "dbname = ", db , " sslmode=require sslcert=", certs_path ,
  "/certs/postgresql-", username ,".crt sslkey=", certs_path ,
  "/certs/postgresql-", username,".key", " dbname = ", db ),
  user = username
)
```
Then I could run commands like this successfully:
```
mytable_on_db <- src_pool ( pool ) %>% tbl (sql("select * from myschema.mytable")  )
mytable_on_db %>% collect()
```
Constructing the SQL statement using the `sql()` call that way allows joins across schema when using`src_postgres()` to make database connections (which has been our practice). In contrast, giving the `options = '-c search_path = myschema'` to `src_postgres()`  produces the dreaded "Error: x and y don't share the same src" error message from dplyr join statements if the tables are not in the same schema. Unfortunately, that error message came back using src_pool. Maybe, once again, I'm doing something the wrong way? [This seems like it might be a different issue. I can start another ticket.]

Thanks!

**Comment by bborgesr** [comment]
Can you give me the code that is working in postgres (without `src_pool`) and the equivalent code that fails with `scr_pool`? I'm having a hard time understanding where you're problem might be coming from.

**Comment by koseri** [comment]
## Using `src_pool()`
```

username <- "foo"

pool_new <- dbPool(
  drv = "PostgreSQL",
  host = db_host,
  dbname =   paste0( "dbname = ", db , " sslmode=require sslcert=", home_path ,
                     "/.../postgresql-", username ,".crt sslkey=", home_path ,
                     "/.../postgresql-", username,".key", " dbname = ", db ),
  user = username
)

wave_db <- src_pool ( pool_new ) %>% tbl (sql("select * from schA.wave")  )
r_age_db <- src_pool ( pool_new ) %>% tbl (sql("select * from schB.r_age")  )
```

This
```
r_age_db %>% left_join ( wave_db %>% rename ( wave_id = id), by = "wave_id")
```
produces
> Error: x and y don't share the same src. Set copy = TRUE to copy y into x's source (this may be time consuming).

And just to be certain of the results further below, I also ran this (i.e. added the collects)
```
r_age_db %>% collect() %>% left_join ( wave_db %>% rename ( wave_id = id) %>% collect(), by = "wave_id")
```

## Using `src_postgres()`

```
db_name_string_foo <- paste0( "dbname=foodb sslmode=require sslcert=" , home_path , "/.../postgresql-foo.crt sslkey=", home_path, "/.../postgresql-foo.key" )

old_con <- src_postgres ( dbname = db_name_string_foo, host = db_host, user = "foo")

old_wave_db <- tbl (old_con, sql("select * from schA.wave")  )
old_r_age_db <- tbl( old_con, sql("select * from schB.r_age"))
```

The statement below produces exactly the same result as the one using collects above and does not require collection:
```
old_r_age_db %>% left_join ( old_wave_db %>% rename ( wave_id = id), by = "wave_id")
```

**Comment by bborgesr** [comment]
Ok, I get it now. I don't think this is an issue with `pool`. `dplyr` just doesn't currently allow for cross-schema joints, unless you copy the data around. From a quick search, it seems other people have also showed an interest to change this (ex: [this issue](https://github.com/rstats-db/bigrquery/issues/101)). So, if that is something you feel should be supported by `dplyr`, you should post an issue there.

However, there two easy solutions to your particular problem here:

1) Use `left_join(..., copy = TRUE)`:

```r
library(dplyr)
library(pool)

pool <- dbPool(
  drv = RMySQL::MySQL(),
  dbname = "shinydemo",
  host = "shiny-demo.csa7qlmguqrf.us-east-1.rds.amazonaws.com",
  username = "guest",
  password = "guest"
)

db1 <- src_pool(pool) %>% tbl("country")
db2 <- src_pool(pool) %>% tbl("countrylanguage") %>% rename(code = countrycode)

join <- db1 %>% left_join(db2, copy = TRUE)
```

2) Use the same pattern you demoed above for `src_postgres` with `src_pool` (i.e. call `src_pool` just once and use that same resulting object to call `tbl` in two separate calls):

```r
library(dplyr)
library(pool)

pool <- dbPool(
  drv = RMySQL::MySQL(),
  dbname = "shinydemo",
  host = "shiny-demo.csa7qlmguqrf.us-east-1.rds.amazonaws.com",
  username = "guest",
  password = "guest"
)

srcPool <- src_pool(pool)
db1 <- srcPool %>% tbl("country")
db2 <- srcPool %>% tbl("countrylanguage") %>% rename(code = countrycode)

join <- db1 %>% left_join(db2)
```

**Comment by bborgesr** [comment]
@hadley, if you have a minute, could you weigh in here? Is this expected behavior in `dplyr`? Or are we missing something in `pool`? Thanks!

**Comment by hadley** [comment]
I'd say the the problem is that you're creating multiple sources, and dplyr doesn't know how to figure out they're the same. Just reuse one source:

```R
library(dplyr)
library(pool)

pool <- dbPool(
  drv = RMySQL::MySQL(),
  dbname = "shinydemo",
  host = "shiny-demo.csa7qlmguqrf.us-east-1.rds.amazonaws.com",
  username = "guest",
  password = "guest"
)
src <- src_pool(pool)
db1 <- src %>% tbl("country")
db2 <- src %>% tbl("countrylanguage") %>% rename(code = countrycode)
```

**Comment by bborgesr** [comment]
And just to be safe, I went head and created two different schemas and tried the same approach, and it works. So I'm not sure why you're experiencing this problem. In summary, while `dplyr` does not allow for cross-source joints, cross-schema joints are fine if they share the same source (I think I didn't make that clear above).

Feel free to play around with this dataset using the `guest` credentials (`user = "guest"` and `password = "guest"` also). 

First to confirm that we have different schemas, you can use `psql` and `\dn`:
```
$ psql --host=postgresdemo.cfd8mtk93q6a.us-west-2.rds.amazonaws.com --port=5432 --username=guest --password --dbname=postgresdemo
Password for user guest: 

psql (9.5.3, server 9.5.2)
postgresdemo=> \dn
 List of schemas
  Name  | Owner  
--------+--------
 public | master
 scha   | master
 schb   | master
(3 rows)
```

Then, in R, the following works:

```r
library(dplyr)
library(pool)

pool <- dbPool(
  drv = RPostgreSQL::PostgreSQL(),
  dbname = "postgresdemo",
  host = "postgresdemo.cfd8mtk93q6a.us-west-2.rds.amazonaws.com",
  user = "guest",
  password = "guest"
)

srcPool <- src_pool(pool)

db1 <- srcPool %>% tbl(sql("select * from scha.country"))
db2 <- srcPool %>% tbl(sql("select * from schb.countrylanguage")) %>% rename(code = countrycode)

join <- db1 %>% left_join(db2)
```

**Comment by koseri** [comment]
Yes! It works this way. Many thanks!!

Note for others who might be stuck... And yet, I _still_ had the following mental stumbling block to get over to prove it to myself:
_Re-creating_ what **look** like identical objects in the same way is not the same as them _being_ the same objects when it comes to _connections._ 

In other words: **Re-using the result of `src_pool()` is not the same as creating a connection on the fly each time even with identical arguments** because the src_pool returned objects really are different things each time they are created. (It was really just a problem of not noticing that I was already re-using the result of `src_postgres()` each time I called `tbl()` and my "translation" to the `pool()` way was not a good translation.)

In code:
```
> identical( src_pool ( my_pool ), src_pool ( my_pool )  )
[1] FALSE
```

Anyway, the right way is far simpler, so again, _thanks_!
