### ISSUE TITLE
Returning a checked-out RPostgreSQL connection returns unsuppressable "no transaction" warning

### ISSUE THREAD

**Issue by ClaytonJY** [rstudio/pool#15]
I'm developing a shiny app which instantiates a `dbPool` in `global.R` with `drv = RPostgreSQL::PostgreSQL()`. Because using `dplyr` leads to inefficient nested subqueries, I frequently use `poolCheckout` so I can send better queries using plain `DBI` functions. When returning the connection with `poolReturn`, everything seems to work, but I get a console message:

    WARNING:  there is no transaction in progress

This wouldn't bother me much if I could simply suppress that message, but it's definitely not a warning, and while it _looks_ like a message (blue text in rstudio), wrapping with `suppressMessages` has no effect.

If I create the connection with `dbConnect`, `dbDisconnect` does _not_ throw that message, so I think this is coming from the interaction of `poolReturn` and `RPostgreSQL`. Is there something I can do differently, or can/should this be fixed in `pool`?

I wish I knew enough to dig deeper into this issue, but I'm pretty inexperienced with R's OO in general and `R6` in specific; I'd be happy to do more given a nudge in the right direction! Should I try using https://github.com/rstats-db/RPostgres? The failing build tag has made me not bother thus far.

**Comment by bborgesr** [comment]
Could you re-install `pool` (using `devtools::install_github("rstudio/pool")`) and try again? I just merged some updates. I can see this issue with some older code, but not with the newest version. Let me know if this solves it.

**Comment by ClaytonJY** [comment]
@bborgesr  *facepalm* yup, that fixed it! Not sure why I didn't do that first, but it's cool to see this package develop rapidly. Thanks!
