### ISSUE TITLE
Helper functions for use in packages

### ISSUE THREAD

**Issue by jl5000** [rstudio/pool#170]
Re: #135 (avoiding pool leak warnings)

Would it be possible to have a helper function(s) (much like those found in `usethis`) which automatically sets up the code snippets like the one recommended in that issue? I imagine wanting to use `pool` in a package will be a common use case and it would be good to make this straightforward for a user.

**Comment by hadley** [comment]
I'm not sure a helper is very useful for two function calls?

**Comment by jl5000** [comment]
The reason why I ask is because it's still not very clear to me how to implement it, and it also requires people to hunt down that specific issue in the Github repo and copy the code. I thought it would be a good idea to make it easier for people to implement best practice in their packages without pool leaks.

**Comment by hadley** [comment]
I think the place to start would be to clearly document in `poolCreate` and `dbPool` that you should always close them after use with `poolClose()`.
