### ISSUE TITLE
No function correspond to methods exports for dbAppendTableArrow failing Docker install

### ISSUE THREAD

**Issue by beskoonlog** [rstudio/pool#178]
When shiny app locally using pool, the following warning appears: 
Warning: no function found corresponding to methods exports from ‘pool’ for: ‘dbAppendTableArrow’, ‘dbCreateTableArrow’, ‘dbGetQueryArrow’, ‘dbReadTableArrow’, ‘dbSendQueryArrow’, ‘dbWriteTableArrow’.

For docker deployment using rocker/shiny-verse:4.2 as the starting image, this causes the package to not be installed and subsequent deployment issues.

**Comment by hadley** [comment]
I think this means I forgot to bump the required DBI dependency. If you use the latest version of DBI, this probably should go away.

**Comment by christophscheuch** [comment]
I had the same issue in the build pipeline for my Docker containers. Indeed, once I made sure that my container has DBI 1.2.1, then pool 1.0.2 installed successfully.
