### ISSUE TITLE
Support for RSQLServer

### ISSUE THREAD

**Issue by jfredtx** [rstudio/pool#20]
As far as I understand, the **RSQLServer** package creates a SQL backend to **dplyr** for connections to a MS SQL Server. The package creates the function `src_sqlserver` which is not one of the three standard types within the **dplyr** package. When I run the command `src_pool(pool) %>% tbl("TableName") %>% head(5)` as in the example using a pool connection created with the `RSQLServer::SQLServer()` driver it returned the following error:

> Error in UseMethod("tbl") : 
>   no applicable method for 'tbl' applied to an object of class "c('src_', 'src_sql', 'src')"

Upon examination of the `src_pool` function in the package code, I notice that the `pool$state$drv` is being set based on one of the three possible drivers that are supported by **dplyr**.  Thus, I created a separate function based on `src_pool` that replaces the `drv` variable with the string `"sqlserver"`.

It seems that an additional if statement in the `dbPool` function (above the `src_pool` function) that assigns the `pool$state$drv` value would fix this error easily - of course the latest **RSQLServer** package would need to be installed.

This package was the only way that I could find to connect to MS SQL Server and have a dplyr backend. Would it be possible to add the appropriate conditional statements to the `dbPool` function to support the `src_sqlserver` command from the **RSQLServer** package?

Example code, slightly modified `src_pool` function, and it returns the correct results:

```
src_pool_sqlserver <- function(pool2) {
    if (!requireNamespace("dplyr", quietly = TRUE)) {
      stop("dplyr package required", call. = FALSE)
    }
    gc()
    drv <- "sqlserver"
    conn2 <- poolCheckout(pool2)
    info <- dbGetInfo(conn2)
  dplyr::src_sql(drv, conn2, info = info, disco = NULL)
}

src_pool_sqlserver(pool) %>% tbl("TableName") %>% head(5)
```

Note, the pool connection was created as follows:

```
pool<-dbPool(drv=RSQLServer::SQLServer(),
             server="NAME_IN_sql.yaml"
  )
```

**Comment by bborgesr** [comment]
Thanks for such a well-written issue! Normally, I'd think your suggestion is completely reasonable. Unfortunately, the latest version of RSQLServer is not compatible with dplyr (see: https://github.com/imanuelcostigan/RSQLServer/issues/68). This should get fixed any day now (there a PR pending Hadley's approval). So I wonder if we should do any changes now, or wait for the two packages to be released to CRAN. Any thoughts, @jcheng5?

**Comment by jfredtx** [comment]
Good point. I probably should have put the package versions in the code. I am using the development version of both packages - dplyr (0.5.0.9000) and RSQLServer (0.2.99), and they work together. In fact, the development RSQLServer package requires the installation of a development version of dplyr.  I'll leave the decision of whether to update now or wait for CRAN release up to the experts! Thanks again.

**Comment by ClaytonJY** [comment]
I have an issue that may be related to this: when using `pool` + `RSQLServer` with `DBI` functions, any time a connection is returned (either explicitly by me, or implicitly when passing a pool to e.g. `dbGetQuery`), I get a warning 'JDBC does not maintain a list of active results'.

I realize JDBC is a dependency of `RSQLServer` and not pool, but I only get this warning when retuning an `RSQLServer` connection to a pool. Does this belong here, in another `pool` issue, an issue in `RSQLServer`, or some combination?

(I'm on CRAN dev versions of pool/RSQLServer/DBI)

**Comment by bborgesr** [comment]
@jfredtx Since dplyr 0.7.0 drops the use of `src_` completely, I don't think this is relevant anymore.

@ClaytonJY This is a very late reply, but I hope you haven't been seeing that for a while now. If that's still the case, let me know.
