### ISSUE TITLE
[Question] what are the supported DB drivers?

### ISSUE THREAD

**Issue by happyshows** [rstudio/pool#24]
for example, I can use RJDBC/RODBC to connect to Teradata, can I use this package to connect via Teradata driver as well?

**Comment by happyshows** [comment]
just checked the dbPool helper page, it seems that pool is only compatible with DBIDriver/connection types, is it possible to implement the JDBC type?

**Comment by bborgesr** [comment]
The [RJDBC library](https://cran.r-project.org/web/packages/RJDBC/index.html) is DBI compliant. Can you use that?

**Comment by happyshows** [comment]
I was trying to use pool connecting to Teradata, however no success.

see error below:
```
.jaddClassPath("../driver/terajdbc4.jar")
.jaddClassPath("../driver/tdgssconfig.jar")
drv = JDBC("com.teradata.jdbc.TeraDriver","../driver/terajdbc4.jar;../driver/tdgssconfig.jar")

dbPool(
     drv = drv,
     dbname = "xxxx",
     host ="jdbc:teradata://xxxxxx",
     username = "xxx",
     password = "xxx"
 )
```

```
Error in .jcall("java/sql/DriverManager", "Ljava/sql/Connection;", "getConnection",  : 
  argument "url" is missing, with no default
```

**Comment by bborgesr** [comment]
It seems like you're not using the right arg names. Looking at RJDBC, you can see that the args for `dbConnect` are: `drv`, `url`, `user` and `password`. So in your case, this would be:

```r
.jaddClassPath("../driver/terajdbc4.jar")
.jaddClassPath("../driver/tdgssconfig.jar")
drv = JDBC("com.teradata.jdbc.TeraDriver","../driver/terajdbc4.jar;../driver/tdgssconfig.jar")

dbPool(
     drv = drv,
     url ="jdbc:teradata://xxxxxx",
     user = "xxx",
     password = "xxx"
 )
```

Let me know if that works.

**Comment by happyshows** [comment]
Work like a charm! thanks.
