### ISSUE TITLE
src_pool leaks a connection when using RPostgreSQL or RPostgres

### ISSUE THREAD

**Issue by jsteinhart** [rstudio/pool#30]
When I run the code (using a valid DB/credentials):
```R
library(RPostgreSQL)
library(DBI)
library(pool)
library(dplyr)

pool <- dbPool(
  drv=dbDriver("PostgreSQL"),
  host="test",
  dbname = "test",
  user="test",
  password = "test"
)

data <- src_pool(pool) %>% tbl("test") %>% collect()

poolClose(pool)
```

I get:

> Warning message:
> You still have checked out objects. Return them to the pool so they can be destroyed. (If these are leaked objects - no reference - they will be destroyed the next time the garbage collector runs). 

I'm using pool 0.1.0 from GitHub, and RPostgreSQL 0.4-1 and DBI 0.5-1 from CRAN (although I've also tried DBI 0.5-14 from GitHub and RPostgres 0.1-4 from rstats-db on GitHub with the same results).

I'm not sure if this is related to #21 

Am I doing (or expecting) something wrong here?

**Comment by bborgesr** [comment]
Sorry it took me a while to get back to you.

You're not doing anything wrong.

Unfortunately, for this to work as efficiently as possible, `pool` and `dplyr` have to be very well integrated. At the moment, we're still waiting for [a commit in `dplyr`](https://github.com/hadley/dplyr/commit/03bba6a1c2d06e0184b0445e7955f989be6ccef4) to hit CRAN to perfect that integration. Until then, this warning is pretty much unavoidable whenever you're using `dplyr` with `pool`. To be clear, the code works just as well now as it will once the integration is better. It's just that when that moment arrives, you should only see this warning if you're really doing something wrong, and  not every time you use `dplyr`... 

In short, that warning means that you are closing a pool which still has a checked out connection. Right now (i.e. before that commit hits CRAN and we adjust the code in `pool`), it's simply impossible for `dplyr` to return connections back to `pool`. So these remain checked out until they're garbaged collected, which tends to be fairly often... This loses the efficiency edge that `pool` usually has (recycling connections), but the code works just as correctly, and you still get the benefit of connection management. But it's really unsatisfactory. I can't wait for this to all work properly!

This is not really related to #21, those problems involve coordination with other packages (so I guess it *is* related in the sense that coordinating with other packages will always be a pain...)

Have you considered using `suppressWarnings(poolClose(pool))` if the always-present warning message annoys you? Let me know if you can't stand the warning and we may consider removing it until it is actually meaningful again... Sorry I don't have a better answer for you right now...

**Comment by bborgesr** [comment]
Since the last comment, `dplyr` completely revamped its database connection syntax, including the creation of a new package (`dbplyr`). All the `src_*` functions are now gone (from `dplyr` and `pool` as of the merging of #42). Therefore the code above should be (only one line needs changing):

```r
data <- pool %>% tbl("test") %>% collect()
```

There should be no warnings generated anymore.
