### ISSUE TITLE
When the package will be available in the CRAN repositoy?

### ISSUE THREAD

**Issue by marcusos** [rstudio/pool#31]
It's necessary to have to have the dev versions of the Shiny and DBI?

**Comment by bborgesr** [comment]
It's no longer necessary to have the dev versions of any package that `pool` depends on. In fact, it's probably safer to use the stable version as development versions can sometimes introduce breaking changes unexpectedly. `pool` is now very well integrated with `DBI`, `shiny` and `dplyr` (and `dbplyr`). We're planning on releasing to CRAN in the near future.
