### ISSUE TITLE
Hadley thinks the classes are wrong

### ISSUE THREAD

**Issue by bborgesr** [rstudio/pool#32]
From my chat with @hadley (obviously feel free to edit if my transcription missed something...):

1. [this](https://github.com/rstudio/pool/blob/master/R/DBI-pool.R#L16-L18) doesn't seem right to me: you generally shouldn't be defining methods when you own neither the generic nor the class

2. [this](https://github.com/rstudio/pool/blob/master/R/DBI-pool.R#L42-L45) doesn't seem right either: an arbitrary DBI connection won't necessary have DBI metadata?

    You need `setOldClass("Pool")` and then you should bind to Pool rather than DBIConnection like you do in the rest of the package. Or if those are supposed to be specifically for connections returned by the pool, you probably need some wrapper class, like PooledConnection.

3. You should make `dbPool` inherit from DBIConnection. You've implemented all the DBI methods, so you've implicitly made it a DBI connection, and you should you acknowledge to the world that you implement the DBI connection interface.

    **Aside - some thoughts on OO:**
    > You should think of DBIConnection more of an interface than a subclass. So, by "inheriting" from DBIConnection, you're clearly stating that you fulfill the contract of the DBIConnection interface, which you do. (Technically calling it an interface is bit confusing because that makes you thinking of message-passing OO; calling it a concept is more in alignment with terminology of generic function OO.)

     Among other things, this would make implementation of `src_dbi` a lot easier, So we could have something like:

    ```r
    pool <- dbPool(
      drv = RMySQL::MySQL(),
      dbname = "shinydemo",
      host = "shiny-demo.csa7qlmguqrf.us-east-1.rds.amazonaws.com",
      username = "guest",
      password = "guest"
    )
    src <- src_dbi(pool)
    ```

cc @jcheng5

**Comment by hadley** [comment]
I've changed my mind about 3; 1 definitely needs fixing, and 2 probably requires some thought.

**Comment by bborgesr** [comment]
(see #39 for Hadley's issue related to this)

**Comment by bborgesr** [comment]
I'll solve 1 in #44 and I'll leave 2 as is for now. We can revisit it later.
