### ISSUE TITLE
Ability to return the object back to pool while using with dplyr

### ISSUE THREAD

**Issue by karrtikiyer-tw** [rstudio/pool#33]
```
srcPool <- src_pool(pool)
city <- srcPool %>% tbl("City")
country <- srcPool %>% tbl("Country")
city %>% left_join(country, by = c("CountryCode" = "Code"))
```

There should be a way to return srcPool back to the pool using some method. Something like poolreturn. More information on this request can be found at http://disq.us/p/1g8glin.

**Comment by bborgesr** [comment]
With the release of dplyr 0.7.0 and the merging of #42, this is no longer an issue, since there's no more `src_*` functions. I.e. what you have above becomes:

```r
city <- pool %>% tbl("City")
country <- pool %>% tbl("Country")
city %>% left_join(country, by = c("CountryCode" = "Code"))
```
