### ISSUE TITLE
Make compatible with dbplyr

### ISSUE THREAD

**Issue by hadley** [rstudio/pool#39]
1.  The implementation of the dplyr database backends has moved to dbplyr. Most of the generics remain in dplyr, so that existing backends don't break.

2. By inspecting the namespace, you can now easily see what methods you need to override for non-DBIConnections. Here's the complete list

````
 db_analyze
 db_begin
 db_collect
 db_commit
 db_compute
 db_copy_to
 db_create_index
 db_create_indexes
 db_create_table
 db_data_type
 db_desc
 db_drop_table
 db_explain
 db_has_table
 db_insert_into
 db_list_tables
 db_query_fields
 db_query_rows
 db_rollback
 db_save_query
 db_sql_render
 db_write_table
 sql_escape_ident
 sql_escape_string
 sql_join
 sql_select
 sql_semi_join
 sql_subquery
 sql_translate_env
 ````

3.  There are a lot of methods, but most of them simply require you to acquire the connection, then release it when it's done. To make that easier, I've written you this function to generate the wrapper functions:

``` r
 library(dplyr, warn.conflicts = FALSE)
 library(rlang)

pool_wrap <- function(f) {
 f <- enquo(f)

formals <- formals(eval_tidy(f))
 con <- names(formals)[[1]]
 passed_on <- names(formals[-1]) %>%
 set_names() %>% 
 lapply(as_symbol)

body <- expr({
 db_con <- poolCheckout(!!sym(con))
 on.exit(poolReturn(db_con))

UQE(f)(db_con, !!!passed_on)
 })

new_function(formals, body, f_env(f))
 }

pool_wrap(db_analyze)
 #> function (con, table, ...) 
 #> {
 #>     db_con <- poolCheckout(con)
 #>     on.exit(poolReturn(db_con))
 #>     db_analyze(db_con, table = table, ... = ...)
 #> }
 #> <environment: 0x7ff69c8927c8>
 ```

4.  There are at least two exceptions: `copy_to()` and `compute()` will need need to throw an error if `temporary = TRUE` because temporary tables are local to a connection, and there's no guarantee you'll get the same connection back next time.

I'm reasonably certain I've made all the changes to dbplyr to facilitate your Pool, but please let me know if I've missed anything. I'm also happy to hop on a call with you and @jcheng5 to answer any questions that you might have.

**Comment by GrayAlex49** [comment]
Am I correct in assuming that since this is still open, the current pool package is not compatible with dplyr 0.7?  
Running `src_pool(pool) %>% tbl("database_table") %>% head(5)` where pool was created using dbPool as described in the [Using dplyr with pool](https://shiny.rstudio.com/articles/pool-dplyr.html) article returns the error 

> Error: 'src_sql' is not an exported object from 'namespace:dplyr'

Also, the examples in that article dont seem to run using dplyr 0.7

**Comment by bborgesr** [comment]
That's true. I'm working on compatibility right now, but we were out of synch for this release of dplyr (and dbplyr), so running a bit behind.. Sorry for the inconvenience!

If you want to keep using both packages now, the workaround is to use dplyr 0.5.0 (`devtools::install_github("hadley/dplyr@v0.5.0")`) We should have full compatibility very soon though!

**Comment by GrayAlex49** [comment]
@bborgesr No worries, thanks for all yall do.  Just wanted to make sure I hadn't misunderstood.
