### ISSUE TITLE
Should leaked connections be passivated (with a reap task set up) or actually destroyed?

### ISSUE THREAD

**Issue by bborgesr** [rstudio/pool#4]
I feel like the first one makes a whole lot more sense (currently, we have the second one).

Again, consider the app from #3 :

```r
library(shiny)
library(pool)
library(dplyr)

pool <- dbPool(drv = RSQLite::SQLite(), 
               "CollegeScorecard.sqlite")

ui <- fluidPage(
  actionButton("recalc1", "Re-query the database (1st table)"),
  tableOutput("tbl1"),
  actionButton("recalc2", "Re-query the database (2nd table)"),
  tableOutput("tbl2")
)

server <- function(input, output, session) {
  output$tbl1 <- renderTable({
    n <- input$recalc1
    tbl <- src_pool(pool) %>% tbl("data") %>% 
      head(n + 3) %>% 
      select(year, id, school.name, school.state)
    info <- dbGetInfo(pool)
    print(paste("free:", info$numberFreeObjects,
                "taken:", info$numberTakenObjects))
    tbl
  })
  output$tbl2 <- renderTable({
    n <- input$recalc2
    tbl <- src_pool(pool) %>% tbl("data") %>% 
      head(n + 3) %>% 
      select(school.name, student.size)
    info <- dbGetInfo(pool)
    print(paste("free:", info$numberFreeObjects,
                "taken:", info$numberTakenObjects))
    tbl
  })
}

shinyApp(ui, server)
```

Aside from the issue in #3 (let's assume here that was fixed), we're still not getting any performance benefits, because the leaked connections are automatically destroyed upon detection, rather than recycled (i.e. passivated and be ready for activation, at least until the reap task kicks in, depending on the `idleTimeout` param).

I'm pretty sure this change should be uncontroversial...

**Comment by jcheng5** [comment]
That's right. I had decided we should destroy them instead of passivate them because of nondeterministic finalization order. For example, if the connection itself has a finalizer, it could've already run.

**Comment by jcheng5** [comment]
No, I think it may still be unsafe. Let's discuss over vchat sometime.

**Comment by bborgesr** [comment]
Ok, changed it back to destruction in the meantime.

**Comment by bborgesr** [comment]
*Final consensus*: leaked connections should be destroyed because the connection's own finalizer (if it exists -- and by the end of the year every DBI-compliant driver should have this implemented) will be competing with the pool's finalizer. If the connection's finalizer happens to run first, then the pool's finalizer would be trying to passivate something that was already destroyed... It is safer to just try to destroy it (either it destroys it if that finalizer is called first, or does nothing if the connection was already destroyed with another finalizer).
