### ISSUE TITLE
issue connecting to oracle database

### ISSUE THREAD

**Issue by iainmwallace** [rstudio/pool#46]
Hi,

I am trying to use pool to connect to an oracle database and having a slight issue

My current method for connecting that works is
  jdbcDriver <- JDBC(driverClass="oracle.jdbc.OracleDriver", classPath="./ojdbc6.jar")
  jdbcConnection <- dbConnect(jdbcDriver, database, username, password)

I converted that to pool
jdbcDriver <- JDBC(driverClass="oracle.jdbc.OracleDriver", classPath="./ojdbc6.jar")
jdbcConnection <-
  dbPool(
    drv = jdbcDriver, 
    url = database 
    username = username, 
    password = password
    )

Unfortunately I am getting a log in error
Error in .jcall(drv@jdrv, "Ljava/sql/Connection;", "connect", as.character(url)[1],  : 
  java.sql.SQLException: ORA-01017: invalid username/password; logon denied

The username and password are correct - is there another way that I should format the pool request so the username and password get sent correctly?

thanks your help,

Iain

**Comment by bborgesr** [comment]
I think you have the wrong argument name: it should be `user`, not `username`: https://github.com/s-u/RJDBC/blob/master/R/class.R#L39 . Let me know if that doesn't fix it.

**Comment by iainmwallace** [comment]
Thanks - that worked!
