### ISSUE TITLE
Embed pool in `dplyr::tbl`, not the raw connection

### ISSUE THREAD

**Issue by russellpierce** [rstudio/pool#54]
When I create a dplyr::tbl() the database connection is baked into the resulting object. If my database connection is lost (the db restarted, I opened too many connections and the original connection got pruned, etc), then I can no longer get un-evaluated dplyr SQL back out of the tbl_dbi. Enter package:pool. Surely this will come to my rescue; surely the connection inside the tbl will be evaluated in a lazy fashion and fetched from the pool at runtime. But no such luck, a bare con is baked into the tbl.
```
library(RSQLite)
library(DBI)
library(dplyr)
library(pool)
dbPool(
  RSQLite::SQLite(), 
  dbname = ":memory:",
  validateQuery = "select 10"
) %>% 
  tbl(sql("select 1")) %>% 
  str()
```
If I'm using package:pool incorrectly and there is a right way to do this, please let me know. If I've an unreasonable expectation of what pool should do here, please let me know. I'd originally created an issue on dplyr (https://github.com/tidyverse/dplyr/issues/3184), but Hadley recommended I open an issue on this passage instead.

**Comment by russellpierce** [comment]
The idea is that in an interactive session I might define a tbl based dplyr chain and assign the result, but not collect it. Walk away for the day, and come back to lost connections and useless tbls. 

Another case is predefining a bunch of tbls that will be joined against each other and manipulated this way and that. One wants dplyr to consider the tbls to be using the same source (for joining) but at some point in practice I'm finding RPostgres gets quite cross with the whole thing and starts closing the connections in the tbls rendering them useless.

**Comment by bborgesr** [comment]
Why not just encapsulate the whole `tbl` logic into a function that is called each time? This will get you the behavior you need with no changes to either codebase. (I haven't really thought about whether or not this should be a feature in `pool`, but this seems like the best answer to your problem at the moment):

```r
library(DBI)
library(dplyr)
library(pool)

pool <- dbPool(
  RSQLite::SQLite(), 
  dbname = ":memory:",
  validateQuery = "select 10"
)

myTbl <- function() {
  pool %>% tbl(sql("select 1"))
}

myTbl() %>% str

# this ensures that the previous connection is busy,
# so that we can be sure that `myTbl` works when the
# first connection isn't available
conn <- poolCheckout(pool)

myTbl() %>% str
```

**Comment by russellpierce** [comment]
Sounds like a good idea. I'd tried something similar and didn't enjoy the result. may give it another shot just to unblock.

I thought it ended up looking pretty ugly because the whole tbl definition moves from a first class dplyr chain to being part of the function call.

E.g., using your example,

```
myTbl <- function(tbl_source, functional_chain) {
  pool %>% tbl(tbl_source) %>% functional_chain
}

myTbl("table1", . %>%
  filter(blah == "Foo") %>%
  mutate(c = a + b)
) %>%
left_join(myTbl("table2", . %>%
  filter(blah = "bar") %>%
  rename(c = d)),
by = "c")
```
(Made even uglier by writing on mobile, sorry)

Some of the ugliness there might be addressed by myTbl returning functions rather than tbls (but it seems like that might cause other issues).  

Regardless of beauty, it seems like incremental composability also suffered. Using tbl() in the raw, lacking connection issues, you can do nice things like a function taking two tbls as args and do fun things with them. Now I can do that, but I have to be ready to consume the result before I run into connection issues.

**Comment by hadley** [comment]
I have a vague feeling that I looked into this at some time in the past, and it was very fiddly. But that was several years ago and it seems like I didn't record my discoveries anywhere I can find them, so I think it's worth trying again.

**Comment by hadley** [comment]
Not sure when this changed, but we are embedding the pool in the tbl objects, not a checked out connection.
