### ISSUE TITLE
RPostgreSQL only emits warnings

### ISSUE THREAD

**Issue by megatron-me-uk** [rstudio/pool#56]
When validating a connection, it is refreshed only when encountering an error. Currently RPostgreSQL internally catches all errors and downgrades them to warnings. Could it be possible to force the pool to refresh a connection when it encounters a warning on validation?

**Comment by megatron-me-uk** [comment]
The following code works for me: 
```
Pool$set('private', 'checkValidTemplate', function(object, errorFun) {
       tryCatch({
         onActivate(object)
         private$validate(object)
         return(object)

       }, error = function(e) {
         private$changeObjectStatus(object, NULL)
         errorFun(e)
       }, warning = function(e) {
         private$changeObjectStatus(object, NULL)
         errorFun(e)
       })
     }, overwrite=TRUE)
```

**Comment by hadley** [comment]
Closing since this is very old and you didn't provide a reprex; I presume you've figure out a solution in the subsequent 5 years 😄
