### ISSUE TITLE
Leaked pool objects during development

### ISSUE THREAD

**Issue by baderstine** [rstudio/pool#58]
I've created a single-file app using a pooled connection to a PostgreSQL server, per the instructions on [https://shiny.rstudio.com/articles/pool-basics.html](https://shiny.rstudio.com/articles/pool-basics.html).  When running the app in RStudio, we get many "leaked pool object" notifications when we:
1) run app
2) edit app.R, save, Reload app (repeat several times as developing)

```
> runApp('[path redacted]')

Listening on [localhost IP redacted]
Warning in (function (e)  : You have a leaked pooled object.
Warning in (function (e)  : You have a leaked pooled object.
Warning in (function (e)  : You have a leaked pooled object.
Warning in (function (e)  : You have a leaked pooled object.
```

The pool connection is stored in a local R package function:

```
get_pool() = function() {
     require(pool)
      con = dbPool(RPostgreSQL::PostgreSQL(), [redacted])
     return(con)
}
```

In the app.R code we just call the function to get our pool, e.g., `pool <- get_pool()` in place of storing the connection credentials in the app.R file.

It seems that these localhost pools just get leaked over and over again and never get cleaned up on our PostgreSQL server.  Eventually we surpass the 16-connection limit and have to manually kill the leaked connections.  This doesn't seem to happen when we're running the app on its normal server and accessing through a browser.

**Comment by bborgesr** [comment]
You are not using `pool` correctly. Please follow this example (from the [README](https://github.com/rstudio/pool#usage)) for your app. You shouldn't deviate from the way that `pool` is used there (the pool function should be at the top level like that and below, you should just copy-paste the `onStop()` code there into  your app). If you think that you need to, please reply here and I can try to see what's wrong. But `pool` is completely interchangeable with `dplyr` and `DBI`, so I can't imagine why'd you run into problems there.

**Comment by bborgesr** [comment]
Also, you shouldn't have a `get_pool()` function at all, but it is also bad practice to call `require()` inside a function.

**Comment by baderstine** [comment]
Thank you, Barbara.  I was not aware of the readme example.  I was following the examples from the Shiny RStudio website (which do not contain the onStop() code) - https://shiny.rstudio.com/articles/pool-basics.html  and https://shiny.rstudio.com/articles/pool-advanced.html

-Brian

**Comment by zola-25** [comment]
I have this same problem, and my understanding from reading the above thread is that we cannot create the pool object in a separate sourced R script than the shiny app.R, without getting "Warning in (function (e)  : You have a leaked pooled object." messages? 

I have quite a large shiny application and I want to define my database access functions in a separate file from app.R. It seems the only way I can get this to work without the warning messages is to define pool<-dbPool(...) in the app.R and pass this through to the functions in the separate file. Is this the case? Or can the warning messages be ignored?

**Comment by ttzhou** [comment]
Apologies for necromancy, thought I'd leave a possible solution to @zola-25, in case other people are searching for potential solutions.

`globals.R`

```r
library(pool)
library(RPostgres)

# Note this is a publicly available postgres database
# online
DB_CONN <- pool::dbPool(drv = Postgres(),

  host = "hh-pgsql-public.ebi.ac.uk",
  port = 5432,
  user = "reader",
  dbname = "pfmegrnargs"

)
```

`app.R`

```r
library(shiny)
library(DT)
library(dplyr)
library(dbplyr)
library(magrittr)

source("globals.R")

ui <- fluidPage(
    DTOutput("test_tbl")
)

server <- function(input, output) {

    test_data <- DB_CONN %>%
        tbl(in_schema("rnacen", "xref_p41_not_deleted")) %>%
        head(20) %>%
        collect

    output[["test_tbl"]] <- renderDT(test_data)

}

shinyApp(ui = ui, server = server, onStart = function() {
    onStop(function() {
        pool::poolClose(DB_CONN)
    })
})
```

Note that I did not have to use `<<-` to get a global assignment of DB_CONN.
