### ISSUE TITLE
Is there any way to get query execution status information from pool in order create a progressbar ? 

### ISSUE THREAD

**Issue by rohit-gupta** [rstudio/pool#59]
I am currently using Shiny to create a dashboard, and data is being pulled from an SQL database using pool, however queries often take 10+ seconds, which is why I was hoping to create a progressbar. Shiny has a progressbar object however I don't know how to get progress updates for it from pool.

**Comment by hadley** [comment]
This depends on the underlying DBI backend, and unfortunately as far as I know, is not supported anywhere.  Progress bars are hard 😢
