### ISSUE TITLE
Make dsn the default for pool

### ISSUE THREAD

**Issue by nwstephens** [rstudio/pool#60]
It would be nice if I could specify a DSN using pool the same way I use DBI+odbc. Right now if I specify a DSN without a named argument, I get an error. What I would like to see is a connection that recognizes the DSN without the named argument. That way I could easily swap out a DBI connection for a pool connection when I deploy my Shiny app.

If this change isn't possible, I recommend adding an example in the help documentation for people using DSN's with odbc. It's not super clear how that should happen since DBI::dbConnect is masked by odbc::dbConnect. You have to do ?odbc::dbConnect to find the right argument name.

```
# Fails in pool
> con <- pool::dbPool(odbc::odbc(), "Postgres (DSN)")
Error in pool::dbPool(odbc::odbc(), "Postgres (DSN)") : 
  All arguments to `dbPool` must be named

# Succeeds pool
> con <- pool::dbPool(odbc::odbc(), dsn = "Postgres (DSN)")

# Succeeds in DBI
> con <- DBI::dbConnect(odbc::odbc(), "Postgres (DSN)")
```

**Comment by afparsons** [comment]
At a minimum, please add a `dsn` example to the help doc.

**Comment by nwstephens** [comment]
I added an example to the `dbPool` documentation. Hopefully the example is sufficient for using DSN's with `pool`. Consider reopening this issue if confusion persists.
