### ISSUE TITLE
Add ssh tunneling support to databases to pool. 

### ISSUE THREAD

**Issue by ngamita** [rstudio/pool#65]
At the moment i have to run ssh tunneling manually with a line like 

```
`system("nohup ssh -v -f -o StrictHostKeyChecking=no -i ./path/to/id_rsa -N -L 3306:localhost:3306 user@hostname", wait = FALSE, ignore.stdout = TRUE, ignore.stderr = TRUE, input = character(0))
`
```
this in shiny yet it would be catered for when i just add parameters like 

pool <- dbPool(
 drv = RPostgres::Postgres(),
  dbname = "demo",
  host = "localhost",
  port = "5432",
  username = "demo",
  password = "pass"
  ## missing and would be nice to have for the tunneling parameters.
  ssh_host = "demo.host.at"
  ssh_user = "ssh_user"
  ssh_password= "ssh_pass"
  ssh_port="1234"
) 

Additional notes on ssh tunneling with Postgres https://www.postgresql.org/docs/8.2/static/ssh-tunnels.html

**Comment by hadley** [comment]
I think this is out of scope for pool, since it just forwards on the DBI connection parameters.
