### ISSUE TITLE
I am trying to connect to my PostgreSQL in Heroku but it takes forever

### ISSUE THREAD

**Issue by rodguinea** [rstudio/pool#70]
Hello,

Can you help me please with this problem? I am trying to connect to my PostgreSQL database in heroku and when I write the following code:

    library(DBI)
    library(pool)
    library(dbplyr)
    library(RPostgreSQL)
    library(nlme)

    pool <- dbPool(
        drv = dbDriver("PostgreSQL", max.con = 100),
        dbname = "koilos",
        host = "192.241.159.69",
        user = "koilos_db_usr",
        port = "8001",
        password = "thisisnotthepassword",
        idleTimeout = 36000
    )

RStudio start running to never stop. Then I have to forced it to close.

I already installed:
    devtools::install_github("rstudio/pool")

Thank you!
Rodrigo

**Comment by hadley** [comment]
Closing since this is very old; I presume you've figure out a solution in the subsequent 4 years 😄
