### ISSUE TITLE
Do I need to close pool when using in future statement of a shiny app?

### ISSUE THREAD

**Issue by shizidushu** [rstudio/pool#75]
Here is some code from a shiny app
```r
future({
      pool <- do.call(pool::dbPool, c(list(drv=odbc::odbc()), db_args))
      df <- dbGetQuery(pool, query)
      pool::poolClose(pool)
      df
    })
```

Should I use pool::poolClose(pool) as shown in above?

**Comment by dpmccabe** [comment]
I don't see the benefit of creating a pool just to run a single query. I would just call `dbConnect` and `dbDisconnect` inside the block.

**Comment by shrektan** [comment]
what’s more, use `on.exit(close())` is even better.

**Comment by shizidushu** [comment]
@shrektan Thanks. I like this idea.
