### ISSUE TITLE
Does pool work on DB2?

### ISSUE THREAD

**Issue by LNsanpython** [rstudio/pool#78]
Hi, 
I am trying to build a shiny app that retrieves data from DB2, 

I have been using RJDBC, and also find ibmdbR to be useful in the testing phase. But since this is an enterprise application, with an expected user base of 300, I would like to use the pool option, I am not aware of how the pooling is done within ibmdbR, as I am still reading it up. 
Please help me understand the scope of this package and I will be extremely happy to post back the solution.
Thanks
Leena

**Comment by s-fleck** [comment]
imdbR uses the somewhat outdated **RODBC** package as a backend. I am not sure which extra features ibmdb2 provides, but you will probably get better perfomance and features out of just using the newer package **odbc** direclty to connect to the DB2, and im sure pool will be supported then.
