### ISSUE TITLE
"SELECT 1" in onValidate method fails

### ISSUE THREAD

**Issue by trinovantum** [rstudio/pool#8]
onValidate method in DBI-pool.R sends "SELECT 1" statement though dbGetQuery to the pool for validation. This is an invalid SQL statement. I am connecting to a IBM DB2 database using RJDBC. The pool is created successfully with dbPool, but when I try to use it I get the following error (as expected):

_Error in .verify.JDBC.result: Unable to retrieve JDBC result set for SELECT 1 (DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=END-OF-STATEMENT;SELECT 1;<table_expr>, DRIVER=3.69.49)_

"VALUES 1" is SQL ANSI standard

Thanks

**Comment by bborgesr** [comment]
Sorry it took me a while to get back to you. `SELECT 1` works for most DBMS (see this [StackOverflow post](http://stackoverflow.com/questions/3668506/efficient-sql-test-query-or-validation-query-that-will-work-across-all-or-most)), but unfortunately not for all... So I added some code to deal with this. 

Right now, you have two options. Use exactly the same code as before. This time, however, `pool` will try to guess which check works by trying of few possibilities (including `SELECT 1` *and* `VALUES 1` -- so in your case, this will work). Or, if you want to be extra sure that it will use a valid SQL check for you particular DBMS, you can now also provide an additional, optional argument to `dbPool` (called `validateQuery`) that provides the query that should be used. E.g.:

```r
pool <- dbPool(
  drv = RMySQL::MySQL(),
  dbname = "shinydemo",
  host = "shiny-demo.csa7qlmguqrf.us-east-1.rds.amazonaws.com",
  username = "guest",
  password = "guest",
  validateQuery = "SELECT 1"
)
```

Hope this solution works for you

**Comment by trinovantum** [comment]
Many thanks for your answer and work around. 

Regards
