### ISSUE TITLE
pool not working in R 3.5

### ISSUE THREAD

**Issue by CosteaPaul** [rstudio/pool#84]
Looks sort of similar to #80 , but on 3.5.1

library(pool)
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  lazy-load database '/usr/local/lib/R/site-library/assertthat/R/assertthat.rdb' is corrupt
Calls: <Anonymous> ... with.default -> eval -> eval -> with_envvar -> force -> run
In addition: Warning message:
In run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  :
  internal error -3 in R_decompress1

Any help would be great! :)

**Comment by schloerke** [comment]
Looks like your assertthat R package can't be loaded.  

Try: `library(assertthat)`.  I'm guessing it will fail.

In a new R session, I'd remove assertthat then reinstall it.  Should solve the problem.

```r
remove.packages("assertthat")
remove.pacakges("learnr")
install.packages("assertthat")
install.packages("learnr")
```

**Comment by schloerke** [comment]
(closing as unrelated to pool)
