### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by jcpsantiago** [rstudio/pool#86]
I'm using pool within a Shiny app written as a package. The pool and app are launched like this:

```R
library(myapp)
message("Starting the connection pool...")

pool <- pool::dbPool(
  drv = RMariaDB::MariaDB(),
  dbname = Sys.getenv("DWH_DBNAME_MYSQL"),
  host = Sys.getenv("DWH_HOST_MYSQL"),
  user = Sys.getenv("DWH_USER_MYSQL"),
  password = Sys.getenv("DWH_PASSWORD_MYSQL"),
  minSize = 10,
  idleTimeout = 3600000
)

shiny::onStop(function() {
  message("Closing the connection pool...\nBye-bye!")
  pool::poolClose(pool)
})

myapp::run_app()
```

and this is the function I use to fetch data:
```R
get_db_data <- function(query, con = pool) {
  if (!inherits(con, "Pool")) {
    stop("Please start a connection pool first with get_pool.")
  }
  
  if (is.null(query)) {
    stop("Please give me a SQL query as a character string, 
    otherwise I can't fetch any data o(╥﹏╥)o")
  }
  
  # glue replaces templated queries e.g. select * from {table}
  glued_query <- glue::glue_sql(query, .con = con, .envir = parent.frame())
  pool::dbGetQuery(con, glued_query)
}
```

After having the app open for a while, if I try to fetch new data I get:
`Warning: Error in result_create: MySQL server has gone away [2006]`
everywhere where data from the database should be. I tried increasing the number of connections and idle timeout, but I don't see a difference.

Theoretically, is this an issue on `pool`'s side or the server I'm connecting to?

**Comment by millerh1** [comment]
I get this error constantly -- has there been any update?

**Comment by davelorino** [comment]
Also dealing with this issue.

**Comment by jcheng5** [comment]
That means the server is closing the connection due to idle timeout. If your database server implements idle timeout, I would set `minSize` to `0` and `idleTimeout` to some number _less than_ whatever you think the server's timeout is. Basically, you want `pool` to close the connection before the server decides to.

**Comment by davelorino** [comment]
Thank you!

**Comment by narensahu13** [comment]
@davelorino Does the above solve your issue? i am having a similar problem. What did you set `idleTimeout` ?
I have not tried the above solution yet.
