### ISSUE TITLE
postgis and pool

### ISSUE THREAD

**Issue by thmschk** [rstudio/pool#87]
So far, I only used RPostgreSQL and Rpostgis to load data and shapes to my shiny app. 

```
library(RPostgreSQL)
library(rpostgis)

assign("congis", dbConnect(dbDriver("PostgreSQL"),
                          dbname = 'db', 
                          host = "dbhost", 
                          port = 5432, 
                         user = "user", 
                         password = "pw"), 
             envir = .GlobalEnv)

assign("shapes",pgGetGeom(congis,query="SELECT * from xxx",geom="geom"),envir = .GlobalEnv)

```

I have now switched to pool, which makes my request way more convenient. However,  I cannot use pgGetGeom() anymore using pool with

```
congis <- pool::dbPool(
	drv = RPostgres::Postgres(),
	dbname = "db",
	host = "dbhost",
	port = 5432,
	user = "user",
	password = "user")
```
Does anyone know if this is a Rpostgis issue or is it, because Rpostgis is not supported in R Pool?

**Comment by plorch** [comment]
Did you resolve this?  I have the same question.

**Comment by laurenzo-git** [comment]
Unfortunately, no... So far, I set up two connections, one with RPostgres and one with RPostgreSQL. Certainly not a satisfactory solution.

**Comment by plorch** [comment]
I’ve just done the same. 

     -Pat

**Comment by hadley** [comment]
You didn't report the error, but I suspect you might need to use `poolCheckout()` and `poolRelease()` manually yourself.
