### ISSUE TITLE
unable to use dbSendStatement

### ISSUE THREAD

**Issue by Jazelle759** [rstudio/pool#88]
I tried running the following code but encountered an error. I have no problem with dbSendStatement if I use dbConnect, but I am wondering what should I do to use dbSendStatement when using pool.

```
db_pool <- pool::dbPool(drv = RMariaDB::MariaDB(),
                        default.file=dbConfigFile,
                        groups="test_database",
                        ssl.capath=certs_folder,
                        ssl.key=file.path(certs_folder,"client-key.pem"),
                        ssl.cert=file.path(certs_folder,"client-cert.pem"),
                        ssl.ca=file.path(certs_folder,"server-ca.pem"))

send_update <- dbSendStatement(db_pool, update_query) 
```

Error message
```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbSendStatement’ for signature ‘"Pool", "character"’
```

**Comment by antoine-sachet** [comment]
Correct, pool does not implement `dbSendStatement`. You have 3 options:

1. Use `dbExecute` instead (unless you had good reasons to use `dbSendStatement` - if you don't know then you're fine to use `dbExecute`). You can check `?DBI::dbSendStatement` and `?DBI::dbExecute` for more info.

2. Check out a connection from the pool (with `pool::poolCheckout`) and call `dbSendStatement` on it. Remember to return the connection to the pool (with `pool::poolReturn`) when you're done. If you code is not interactive, use `on.exit(pool::poolReturn(db_con))` immediately after checking out the connection to make sure it is returned even if you code fails.

3. Send the statement in a transaction: `pool::poolWithTransaction(db_pool, function(db_con) dbSendStatement(db_con, update_query))`. The advantage is roll back on error and automatic connection management.

**Comment by jcheng5** [comment]
I'm implementing a better error message for the next pool release, recommending option 1 (`dbExecute()`).

It's impossible for pool to support `dbSendStatement` or `dbSendQuery` because they return "live" resultset objects, which is not compatible with pooling semantics; by the time the caller gets around to using the resultset object, the underlying connection may have been used for something else. I don't see any downside in using `dbExecute` though.
