### ISSUE TITLE
Why not just close the pool in reg.finalizer if any leak?

### ISSUE THREAD

**Issue by shrektan** [rstudio/pool#95]
I can see pool has register a reg.finalizer() hook to warn any leak connections. However, why not also close them there? It looks like now only a warning is left but no cleaning up action taken.

https://github.com/rstudio/pool/blob/578c8ad06d7b2233e2aed5b43509a14b55640555/R/pool.R#L180-L185

**Comment by hadley** [comment]
I talked this through with @jcheng5 — this is deliberate design decision because, due to when it's run, it's dangerous to run work in a finalizer. In the past this has caused crashes that were extremely hard to debug, so it's better for you to respond to this warning yourself.

**Comment by wch** [comment]
I remember debugging finalizer problems in the past, in #40. It was very challenging to figure out what was going on.

**Comment by shrektan** [comment]
Thanks for the response. So the short answer is there's no simple way to release the resources when garbage collecting in R.
