### ISSUE TITLE
Missing dbQuoteLiteral methods for pool

### ISSUE THREAD

**Issue by fmannhardt** [rstudio/pool#96]
After upgrading to the latest `glue` version (1.3.2), it is incompatible with `pool` and `glue_sql` throws the following error (as already reported here https://github.com/tidyverse/glue/issues/179):

```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbQuoteLiteral’ for signature ‘"Pool", "character"’
```

It looks like this is caused by missing `dbQuoteLiteral` methods in the `pool` package? I think this is the commit that introduced the issue:
https://github.com/tidyverse/glue/commit/3f0c365e98784d68dac6d714154bf03573634c83

**Comment by benif** [comment]
I'm facing the same issue. I can confirm that 1.3.1 does not have this bug

**Comment by Chrisjb** [comment]
I have had this issue too. I can reproduce using:
```
pool <- dbPool(
  drv = PostgreSQL(),
  host = 'localhost',
  dbname = 'mydb',
  user = 'postgres',
  password = 'password'
)

dbWriteTable(con, 'iris', iris)
my_species <- c('setosa', 'versicolor')
query<- glue::glue_sql('
      SELECT * 
      FROM iris
      WHERE Species IN ({my_species*});
                  ',.con = con)
```

> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘dbQuoteLiteral’ for signature ‘"Pool"’

**Comment by kaushiklakshman** [comment]
Adding to this - can also confirm this very same error

**Comment by shrektan** [comment]
adding a "me, too" ...

**Comment by pnacht** [comment]
I've temporarily solved this by creating my own `dbQuoteLiteral` method for `pool` and adding it to my personal utilities package. It is effectively identical to `pool`'s own `dbQuoteString` and `dbQuoteIdentifier` methods.

```r
#' @importMethodsFrom DBI dbQuoteLiteral
#' @importFrom pool poolCheckout poolReturn
#' @export
setMethod("dbQuoteLiteral", c("Pool", "ANY"),
         function(conn, x, ...) {
           # As of 2020-05-07, this is necessary due to an incompatiblity
           # between packages `pool` (v 0.1.4.3) and `glue` (v >= 1.3.2).
           # In v1.3.2, `glue` started using `dbQuoteLiteral`, which is
           # currently not offered by `pool`, so creating it here.
           connection <- pool::poolCheckout(conn)
           on.exit(pool::poolReturn(connection))
           DBI::dbQuoteLiteral(connection, x, ...)
         }
)
```

**Comment by dpprdan** [comment]
Could you open a PR with your `dbQuoteLiteral` method? (I am not a {pool} developer, but this looks right, IMHO).

**Comment by thuyetbao** [comment]
I has the same issue and your work is worked. (y)

**Comment by shizidushu** [comment]
The check of @pnacht 's PR is failed. The log shows:
```bash
$ curl -fLo /tmp/texlive.tar.gz https://github.com/jimhester/ubuntu-bin/releases/download/latest/texlive.tar.gz

curl: (22) The requested URL returned error: 429 too many requests

The command "eval curl -fLo /tmp/texlive.tar.gz https://github.com/jimhester/ubuntu-bin/releases/download/latest/texlive.tar.gz " failed. Retrying, 2 of 3.
```

It seems Github refused to respond to the download file request. It may be working if rerun.

Now I have to add @pnacht 's code snippet in `Rprofile.site`.  @jcheng5 @bborgesr Could you review the PR and merge it if it looks good?

**Comment by pnacht** [comment]
@shizidushu It's worth mentioning this was literally my first PR ever, so it's entirely possible I configured or did something incorrectly.

**Comment by jcheng5** [comment]
Thank you for this contribution! And sorry for the delay, everyone. I'll review and merge this early next week.
