### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by ImSanjayChintha** [rstudio/pool#97]
I have migrated to MySQL v8.0.19 . I am facing some issues with pool connection as below:

R SQL connection ppol:

```
library(pool)
library(DBI)
library(RMariaDB)

pool = dbPool(
  drv=MariaDB(),
  dbname="mydb",
  username="root",
  password=Sys.getenv("MYSQL_PASSWORD"),
  host="localhost",
  sslmode = 'require',
  port=3306
)
```

```
statement = paste0("select * from Employee where Id IN (", ids ,")")
con3 = poolCheckout(pool)
x = dbGetQuery(con3,statement) //Throwing Error here
poolReturn(con3)

But it is working when I changed same code to :
statement = paste0("select * from Employee where Id IN (", ids ,")")
con3 = poolCheckout(pool)
x = dbGetQuery(pool,statement) //Not getting any issue like this
poolReturn(con3)

```

Is it I am doing in wrong way?

**Comment by ImSanjayChintha** [comment]
Oops... This issue is caused because I am using future and promise packages in my application. Does anyone know how to write MySQL join queries within future packages?

**Comment by hadley** [comment]
In general, it's very hard to use a connection in a different process, so it's unlikely you'll have much success combinig future/promise with pool in this way.
