### ISSUE TITLE
How to set isolation level using pools?

### ISSUE THREAD

**Issue by mmccarthy404** [rstudio/pool#98]
I'm looking to set the isolation level of all read transactions of a pool to "READ UNCOMMITTED" while talking to our production database. I've looked into odbc's odbcSetTransactionIsolationLevel, however, it seems as though that will only work with connections directly, not pools.

Please advice on the best way to get this accomplished!

**Comment by hadley** [comment]
To support this, I think we'd need some way to register a function that's called every time a new DB connection is created.

**Comment by hadley** [comment]
Maybe `onCheckout()` and `onReturn()` arguments to the pool class?

**Comment by hadley** [comment]
Don't even need to change the class; just add a helper to `dbPool`.

**Comment by schafnoir** [comment]
Just discovered the 'pool' package yesterday, and I appreciate how much it has improved the performance of my Shiny app as it interacts with a PostgreSQL database. One minor suggestion for the `dbPool` help page: It would be great to see the example code above with respect to how to properly use the `onCreate` argument. Thanks for all the great development work!
