### ISSUE TITLE
Fixes to the articles on https://shiny.rstudio.com/articles/pool-basics.html

### ISSUE THREAD

**Issue by daattali** [rstudio/pool#99]
I was just reading over the two articles on shiny's website and noticed some mistakes. I think it might be worthwhile to have someone go over the text and do some copy editing because some sentences don't flow well, but here are some of the suggestions I had. I couldn't find any place where I can make a PR.

- "gonna" -> "going to"
- "github" -> "GitHub"
- both pages say that `pool` must be installed from github and show the code for installing from github, but that's no longer true and should install from CRAN
- "there is a brand new package," this package is 4 years old now, not exactly new :)
- "dont worry about closing pool in shiny" why is it not suggested to close the connection using `onStop()`?
- the article talks about `idleTimeout` as being in milliseconds but it's actually seconds
- "you’re transaction" -> "your"
- "these taken effect" -> "take"
- There's an entire section about "upcoming work in DBI" that will add support for transactions. This has been in CRAN for a few years now and the article should update accordingly

**Comment by wch** [comment]
Thanks for the notes! I'll file this in our private repo for the website.

**Comment by daattali** [comment]
Thanks @wch 

Am I correct in wanting to close the pool connection in `onStop()`? Or is there some reason it isn't currently suggested?

**Comment by wch** [comment]
I'm not an expert in using pool, but I think you're right to close it in `onStop()`. I believe the article was written before Shiny had `onStop()`.

**Comment by daattali** [comment]
@wch there's actually another problem, more pressing. The article on [pool+dplyr](https://shiny.rstudio.com/articles/pool-dplyr.html) has code that simply does not work with newer versions of dbplyr.

```
Cannot embed a reactiveValues() object in a SQL query.

If you are seeing this error in code that used to work, the most likely cause is a change dbplyr
1.4.0. Previously `df$x` or `df[[y]]` implied that `df` was a local variable, but now you must make
that explict with `!!` or `local()`, e.g., `!!df$x` or `local(df[["y"]))
```

The code there should update to work with dbplyr. And I also think it would be useful to document somewhere the fact that reactives cannot be used inside dbplyr code (I'm having this discussion here as well https://github.com/tidyverse/dbplyr/issues/439)

**Comment by hadley** [comment]
@mine-çetinkaya-rundel @wch what do you think about moving these to be vignettes on the pool website instead?
